const FRASES_SANTOS = [
    { frase: "Señor, nos hiciste para Ti, y nuestro corazón estará inquieto hasta que descanse en Ti.", autor: "San Agustín" },
    { frase: "Nada te turbe, nada te espante; todo se pasa, Dios no se muda; la paciencia todo lo alcanza. Quien a Dios tiene, nada le falta. Solo Dios basta.", autor: "Santa Teresa de Jesús" },
    { frase: "Al atardecer de la vida, te examinarán en el amor.", autor: "San Juan de la Cruz" },
    { frase: "La oración es un impulso del corazón, es una simple mirada lanzada hacia el cielo, un grito de gratitud y de amor.", autor: "Santa Teresita del Niño Jesús" },
    { frase: "Señor, hazme instrumento de tu paz. Donde haya odio, ponga yo amor; donde haya ofensa, ponga yo perdón; donde haya duda, ponga yo fe.", autor: "San Francisco de Asís" },
    { frase: "Sé quien eres y serás un incendio en la tierra.", autor: "Santa Catalina de Siena" },
    { frase: "Obra como si todo dependiera de ti, pero confía como si todo dependiera de Dios.", autor: "San Ignacio de Loyola" },
    { frase: "Ora, espera y no te preocupes. La inquietud es inútil. Dios es misericordioso y escuchará tu oración.", autor: "San Pío de Pietrelcina" },
    { frase: "Alma que ora, vive; alma que no ora, muere.", autor: "Santa Faustina Kowalska" },
    { frase: "No tengáis miedo. Abrid, más aún, abrid de par en par las puertas a Cristo.", autor: "San Juan Pablo II" },
    { frase: "No te acostumbres a tratar al Señor de tú sin respeto, ni con fórmulas; ni con llaneza sin cariño.", autor: "San Josemaría Escrivá" },
    { frase: "No todos podemos hacer grandes cosas, pero sí podemos hacer pequeñas cosas con gran amor.", autor: "Santa Madre Teresa de Calcuta" },
    { frase: "La bienaventuranza no consiste en un acto de fe, sino en un acto de visión, que es la inteligencia que ya ve a Dios.", autor: "Santo Tomás de Aquino" },
    { frase: "El camino más seguro para llegar a Dios es imitar a Cristo, el Maestro.", autor: "San Buenaventura" },
    { frase: "Si sufres, mira a la cruz; si dudas, mira a la cruz; si te desesperas, mira a la cruz.", autor: "San Bernardo de Claraval" },
    { frase: "Mira a Cristo, que por ti ha sido despreciado; sigue a Cristo, que por ti se ha hecho pobre; ama a Cristo, que por ti ha sido crucificado.", autor: "Santa Clara de Asís" },
    { frase: "Si el alma contempla la hermosura de Cristo, es atraída por ella, y, despojada de todo, vuela hacia Él.", autor: "San Antonio de Padua" },
    { frase: "El orgullo es la puerta por la que entra el demonio en el alma.", autor: "Santa Brígida de Suecia" },
    { frase: "La caridad es el vínculo de la perfección, porque une a los hombres con Dios y entre sí.", autor: "San Roberto Belarmino" },
    { frase: "La verdadera devoción a María es santa, es decir, que lleva a no ofender a Dios.", autor: "San Luis María Grignion de Montfort" },
    { frase: "Haz, Señor, que mi corazón y mi cuerpo sean inmaculados, para que no me vea confundido.", autor: "Santa Cecilia" },
    { frase: "La Iglesia es pobre, pero tiene a Cristo como su tesoro.", autor: "San Lorenzo" },
    { frase: "Cristo es mi esposo, Él me ha elegido a mí entre todas.", autor: "Santa Inés" },
    { frase: "Señor Jesús, recibe mi espíritu. No les tengas en cuenta este pecado.", autor: "San Esteban" },
    { frase: "Es mejor sufrir por Cristo que reinar sin Él.", autor: "San Sebastián" },
    { frase: "No hagáis el mal, sino el bien; no digáis mentiras, sino la verdad; no robéis, sino dad; no seáis perezosos, sino trabajadores.", autor: "San Juan Bosco" },
    { frase: "La alegría del corazón es la fuerza del alma.", autor: "Santa María Mazzarello" },
    { frase: "No me opongo a la mortificación, pero la caridad es la reina de todas las virtudes.", autor: "Santo Domingo de Guzmán" },
    { frase: "Si los hombres supieran lo que es vivir en la gracia, no temerían ningún sufrimiento.", autor: "Santa Rosa de Lima" },
    { frase: "La caridad bien entendida comienza por uno mismo, pero no termina en uno mismo.", autor: "San Martín de Porres" },
    { frase: "Esclavo de los esclavos para siempre.", autor: "San Pedro Claver" },
    { frase: "Dame almas y llévate el resto.", autor: "San Francisco Javier" },
    { frase: "Es mejor ser un pequeño en el reino de los cielos que un grande en la tierra.", autor: "San Luis Gonzaga" },
    { frase: "He nacido para cosas más grandes.", autor: "San Estanislao Kostka" },
    { frase: "Amar a Dios y hacer que Él sea amado.", autor: "San Juan Berchmans" },
    { frase: "La santidad no consiste en tal o cual práctica, sino en una disposición del corazón que nos hace humildes y pequeños en las manos de Dios.", autor: "Santa Teresita del Niño Jesús" },
    { frase: "Sed pacientes con todos, pero sobre todo con vosotros mismos.", autor: "San Francisco de Sales" },
    { frase: "Yo no tengo miedo, porque Dios está conmigo. Él me ha enviado.", autor: "Santa Juana de Arco" },
    { frase: "Cristo conmigo, Cristo delante de mí, Cristo detrás de mí, Cristo dentro de mí.", autor: "San Patricio" },
    { frase: "Con la fuerza de Dios, vencí al dragón.", autor: "San Jorge" },
    { frase: "¿Quién como Dios?", autor: "San Miguel Arcángel" },
    { frase: "Yo soy Rafael, uno de los siete ángeles que estamos delante del Señor.", autor: "San Rafael Arcángel" },
    { frase: "Nada es imposible para Dios.", autor: "San Gabriel Arcángel" },
    { frase: "Cada vez que quieras, puedes volver al corazón de Dios, porque Él te espera siempre.", autor: "Santa Gertrudis la Grande" },
    { frase: "La oración es el mejor remedio para todas las enfermedades del alma.", autor: "Santa Matilde" },
    { frase: "La verdadera sabiduría es conocer a Dios y amarle.", autor: "San Buenaventura" },
    { frase: "Señor, no busco comprender tu altura, porque no la iguala mi entendimiento; pero deseo entender un poco de tu verdad, que cree y ama mi corazón.", autor: "San Anselmo de Canterbury" },
    { frase: "La ciencia no es más que un camino hacia Dios.", autor: "San Alberto Magno" },
    { frase: "El alma humana es como una chispa del fuego divino.", autor: "Santa Hildegarda de Bingen" },
    { frase: "La prueba del amor es la acción.", autor: "San Gregorio Magno" },
    { frase: "La ignorancia de las Escrituras es ignorancia de Cristo.", autor: "San Jerónimo" },
    { frase: "Cuando se trata de Dios, toda alma que busca encuentra, y toda puerta que llama se le abre.", autor: "San Ambrosio" },
    { frase: "La oración es un ancla para el alma, una luz para el camino.", autor: "San Juan Crisóstomo" },
    { frase: "El Hijo de Dios se hizo hombre para que nosotros pudiéramos hacernos dioses.", autor: "San Atanasio" },
    { frase: "El bautismo es la puerta de la vida espiritual.", autor: "San Cirilo de Jerusalén" },
    { frase: "El pan que retienes es del hambriento; el vestido que guardas es del desnudo.", autor: "San Basilio Magno" },
    { frase: "Recuerda a Dios más a menudo de lo que respiras.", autor: "San Gregorio Nacianceno" },
    { frase: "La fe es la luz del alma, porque sin ella el alma está en tinieblas.", autor: "San Juan Damasceno" },
    { frase: "María es la escala por la cual Dios descendió a la tierra.", autor: "San Sofronio" },
    { frase: "Reconoce, oh cristiano, tu dignidad.", autor: "San León Magno" },
    { frase: "La caridad que no se practica es una caridad muerta.", autor: "San Gelasio I" },
    { frase: "Prefiero morir antes que traicionar la justicia de Dios.", autor: "San Gregorio VII" },
    { frase: "Dios es aquello mayor que nada puede pensarse.", autor: "San Anselmo" },
    { frase: "Si buscas a Dios, búscale en la humildad, no en la altivez.", autor: "San Bernardo" },
    { frase: "El amor de Dios no se mide por las lágrimas, sino por el deseo de agradarle.", autor: "Santa Ángela de Foligno" },
    { frase: "El purgatorio es un fuego de amor divino que quema todo pecado.", autor: "Santa Catalina de Génova" },
    { frase: "La voluntad de Dios es mi paraíso.", autor: "San Cayetano de Thiene" },
    { frase: "La alegría del corazón es la mejor de las penitencias.", autor: "San Felipe Neri" },
    { frase: "La reforma de la Iglesia debe comenzar por la reforma de cada uno de nosotros.", autor: "San Carlos Borromeo" },
    { frase: "La oración es el aliento del alma.", autor: "San Roberto Belarmino" },
    { frase: "No se puede ser cristiano sin la cruz.", autor: "San Pedro Canisio" },
    { frase: "Es cosa de grandísima importancia, para quien comienza a orar, no se desanime.", autor: "Santa Teresa de Jesús" },
    { frase: "En las tinieblas se aprende a amar la luz.", autor: "San Juan de la Cruz" },
    { frase: "La paciencia es la madre de la consolación.", autor: "San Francisco de Sales" },
    { frase: "La caridad es la regla de oro de la vida cristiana.", autor: "San Vicente de Paúl" },
    { frase: "La confianza en Dios es la fuerza del alma.", autor: "Santa Luisa de Marillac" },
    { frase: "La oración es la llave del corazón de Dios.", autor: "San Juan María Vianney" },
    { frase: "Dios es tan bueno que nos espera siempre.", autor: "San Juan Bautista de La Salle" },
    { frase: "María te dice: \"Haz lo que Él te diga\".", autor: "Santa Catalina Labouré" },
    { frase: "La Virgen me dijo: \"No te prometo hacerte feliz en este mundo, sino en el otro\".", autor: "Santa Bernardita Soubirous" },
    { frase: "Predicar la verdad, aunque cueste la vida.", autor: "San Antonio María Claret" },
    { frase: "La humildad es el escudo contra el demonio.", autor: "Santa María Soledad Torres Acosta" },
    { frase: "Es mejor morir que traicionar el secreto de confesión.", autor: "San Juan Nepomuceno" },
    { frase: "La fe es la victoria que vence al mundo.", autor: "San Eduardo el Confesor" },
    { frase: "La misericordia es la corona del rey.", autor: "San Esteban de Hungría" },
    { frase: "La justicia sin caridad es crueldad.", autor: "San Ladislao de Hungría" },
    { frase: "El amor a los pobres es el amor a Cristo.", autor: "Santa Isabel de Hungría" },
    { frase: "Dios es mi único tesoro.", autor: "Santa Eduvigis" },
    { frase: "La pureza del corazón es la llave del cielo.", autor: "San Casimiro" },
    { frase: "La verdad es más fuerte que la muerte.", autor: "San Estanislao de Cracovia" },
    { frase: "Sirvo a Cristo, el Rey de reyes.", autor: "San Wenceslao" },
    { frase: "El amor de Dios es el fuego que enciende el alma.", autor: "San Procopio de Sázava" },
    { frase: "Cristo es mi luz y mi salvación.", autor: "San Vito" },
    { frase: "Llevar a Cristo en el corazón es el mejor viaje.", autor: "San Cristóbal" },
    { frase: "La medicina del alma es la oración.", autor: "San Pantaleón" },
    { frase: "La caridad es la mejor de las medicinas.", autor: "San Cosme y San Damián" },
    { frase: "La luz de Cristo ilumina mi camino.", autor: "Santa Lucía" },
    { frase: "El amor de Dios es un fuego que todo lo consume.", autor: "Santa Inés de Montepulciano" },
    { frase: "La oración es el arma del cristiano.", autor: "Santa Catalina de Ricci" },
    { frase: "El amor de Dios es un abismo sin fondo.", autor: "Santa María Magdalena de Pazzi" },
    { frase: "Restaurar todas las cosas en Cristo.", autor: "San Pío X" },
    { frase: "La paz no es un sueño, es una obligación.", autor: "San Juan XXIII" },
    { frase: "La modernidad consiste en el diálogo con el mundo.", autor: "San Pablo VI" },
    { frase: "La medida del amor es amar sin medida.", autor: "San Juan Pablo II" },
    { frase: "La santidad es la normalidad sobrenatural.", autor: "San Josemaría Escrivá" },
    { frase: "No dejes que tu corazón se enfríe; ve y enciende una llama de amor en el corazón de los demás.", autor: "Santa Teresa de Calcuta" },
    { frase: "Reza y espera. Pero, sobre todo, reza mucho.", autor: "San Pío de Pietrelcina" },
    { frase: "La misericordia de Dios es infinita.", autor: "Santa Faustina Kowalska" },
    { frase: "La única cosa que cuenta es hacer la voluntad de Dios.", autor: "San Maximiliano Kolbe" },
    { frase: "El mundo no necesita lo que tenemos, sino lo que somos.", autor: "Santa Edith Stein" },
    { frase: "El cristiano no puede ser indiferente ante el dolor de su hermano.", autor: "San Óscar Romero" },
    { frase: "Todos nacemos originales, pero muchos mueren como fotocopias.", autor: "Beato Carlo Acutis" },
    { frase: "La Eucaristía es mi autopista al cielo.", autor: "Beato Carlo Acutis" },
    { frase: "La vida es un don que debemos defender siempre.", autor: "Santa Gianna Beretta Molla" },
    { frase: "Si no eres feliz, es porque no amas.", autor: "Santa Teresa de los Andes" },
    { frase: "El cielo es el silencio del alma en presencia de Dios.", autor: "Beata Isabel de la Trinidad" },
    { frase: "La santidad no es hacer cosas raras, sino hacer bien lo cotidiano.", autor: "San Rafael Arnáiz Barón" },
    { frase: "La más hermosa de las oraciones es la del alma que confía en la misericordia de Dios.", autor: "Santa Faustina" },
    { frase: "La vocación cristiana es ser sal y luz del mundo.", autor: "San Josemaría Escrivá" },
    { frase: "La caridad es el corazón del Evangelio.", autor: "San Luis Orione" },
    { frase: "La educación es cosa del corazón.", autor: "San Juan Bosco" },
    { frase: "La alegría de hacer el bien es el mayor de los tesoros.", autor: "Santa María Dominga Mazzarello" },
    { frase: "El predicador debe ser el primer creyente de lo que predica.", autor: "San Juan de Ávila" },
    { frase: "La gloria de Dios es el fin último del hombre.", autor: "San Francisco de Borja" },
    { frase: "La oración es el alimento del alma.", autor: "San Pedro de Alcántara" },
    { frase: "La caridad es la medida de la perfección cristiana.", autor: "San Juan de Ribera" },
    { frase: "La fe mueve montañas, pero el amor las trasciende.", autor: "San Luis Beltrán" },
    { frase: "La verdad no necesita ser defendida con violencia.", autor: "San Pedro Mártir" },
    { frase: "Sin la cruz no hay corona.", autor: "Santa Rosa de Lima" },
    { frase: "La humildad es el camino hacia Dios.", autor: "San Martín de Porres" },
    { frase: "La caridad con los pobres es la mayor de las virtudes.", autor: "San Juan Macías" },
    { frase: "La confianza en Dios es mi única riqueza.", autor: "Santa Mariana de Jesús" },
    { frase: "La educación es el pilar de la sociedad.", autor: "San Miguel Febres Cordero" },
    { frase: "El amor a Jesús es mi única pasión.", autor: "Santa Narcisa de Jesús" },
    { frase: "La voluntad de Dios es mi descanso.", autor: "San Gabriel de la Dolorosa" },
    { frase: "El sufrimiento es el camino hacia el cielo.", autor: "Santa Gemma Galgani" },
    { frase: "El rosario es el arma más poderosa para vencer al demonio.", autor: "San Pío de Pietrelcina" },
    { frase: "No puedo temer a un Dios que se ha hecho tan pequeño por mí.", autor: "Santa Teresita del Niño Jesús" },
    { frase: "Comienza haciendo lo necesario, después lo posible, y de repente estarás haciendo lo imposible.", autor: "San Francisco de Asís" },
    { frase: "Ama a Dios con todo tu corazón y todo lo demás vendrá por añadidura.", autor: "Santa Clara de Asís" },
    { frase: "El amor de Dios es un fuego que enciende el corazón.", autor: "San Antonio de Padua" },
    { frase: "La educación cristiana es la base de la sociedad.", autor: "Santa Ángela de Mérici" },
    { frase: "En la tribulación, busca a Dios; en la prosperidad, dale gracias.", autor: "San Ignacio de Loyola" },
    { frase: "Es necesario sembrar la semilla del Evangelio, aunque sea en tierra dura.", autor: "San Francisco Javier" },
    { frase: "La fe y la razón son como dos alas con las que el espíritu humano se eleva hacia la contemplación de la verdad.", autor: "San Juan Pablo II" },
    { frase: "La caridad es la madre de todas las virtudes.", autor: "San Esteban de Francia" },
    { frase: "Dios es mi capitán y yo su soldado.", autor: "Santa Juana de Arco" },
    { frase: "La fe es la victoria sobre el mundo.", autor: "San Félix de Nola" },
    { frase: "La oración es la llave del cielo.", autor: "Santa Genoveva" },
    { frase: "La gracia de Dios es más poderosa que el pecado.", autor: "San Remigio de Reims" },
    { frase: "Ama a Dios y haz lo que quieras.", autor: "San Agustín" },
    { frase: "La gracia no destruye la naturaleza, sino que la perfecciona.", autor: "Santo Tomás de Aquino" },
    { frase: "El camino hacia Dios es el amor, no el conocimiento.", autor: "San Buenaventura" },
    { frase: "María es la estrella del mar que nos guía al puerto seguro.", autor: "San Bernardo de Claraval" },
    { frase: "La paciencia es la puerta de la santidad.", autor: "Santa Brígida" },
    { frase: "La humildad es la base de todas las virtudes.", autor: "San Roberto Belarmino" },
    { frase: "Todo lo que es de María es de Jesús.", autor: "San Luis María Grignion" },
    { frase: "Mi corazón canta la gloria de Dios.", autor: "Santa Cecilia" },
    { frase: "La Iglesia es pobre, pero tiene el mayor tesoro: a Cristo.", autor: "San Lorenzo" },
    { frase: "Cristo es mi esposo y mi rey.", autor: "Santa Inés" },
    { frase: "Señor, no les tengas en cuenta este pecado.", autor: "San Esteban" },
    { frase: "El martirio es la victoria del amor.", autor: "San Sebastián" },
    { frase: "La alegría es el signo de la santidad.", autor: "San Juan Bosco" },
    { frase: "La caridad es el vínculo de la perfección.", autor: "Santa María Mazzarello" },
    { frase: "El rosario es el arma de los cristianos.", autor: "Santo Domingo de Guzmán" },
    { frase: "La oración es el mejor remedio para todas las enfermedades.", autor: "Santa Rosa de Lima" },
    { frase: "La caridad no conoce fronteras.", autor: "San Martín de Porres" },
    { frase: "El amor a los esclavos es el amor a Cristo.", autor: "San Pedro Claver" },
    { frase: "Es necesario sembrar la semilla del Evangelio en todo el mundo.", autor: "San Francisco Javier" },
    { frase: "La pureza es la belleza del alma.", autor: "San Luis Gonzaga" },
    { frase: "Mi vida es un camino hacia el cielo.", autor: "San Estanislao Kostka" },
    { frase: "La santidad es la meta de mi vida.", autor: "San Juan Berchmans" },
    { frase: "La dulzura es la fuerza de los santos.", autor: "San Francisco de Sales" },
    { frase: "La voluntad de Dios es mi guía.", autor: "Santa Juana de Arco" },
    { frase: "La fe es la luz que ilumina mi camino.", autor: "San Patricio" },
    { frase: "La fe vence al dragón del pecado.", autor: "San Jorge" },
    { frase: "La victoria es de Dios.", autor: "San Miguel Arcángel" },
    { frase: "La curación viene de Dios.", autor: "San Rafael Arcángel" },
    { frase: "La alegría del anuncio es la alegría del Evangelio.", autor: "San Gabriel Arcángel" },
    { frase: "La oración es el corazón de la vida cristiana.", autor: "Santa Gertrudis" },
    { frase: "La humildad es la puerta del cielo.", autor: "Santa Matilde" },
    { frase: "La fe busca entender, pero el entendimiento busca la fe.", autor: "San Anselmo" },
    { frase: "La ciencia es un camino hacia Dios.", autor: "San Alberto Magno" },
    { frase: "La creación es un libro que habla de Dios.", autor: "Santa Hildegarda" },
    { frase: "La caridad es el alma de la Iglesia.", autor: "San Gregorio Magno" },
    { frase: "La Palabra de Dios es la luz del alma.", autor: "San Jerónimo" },
    { frase: "Donde está Pedro, está la Iglesia.", autor: "San Ambrosio" },
    { frase: "La oración es el diálogo del alma con Dios.", autor: "San Juan Crisóstomo" },
    { frase: "La fe es la luz de la inteligencia.", autor: "San Atanasio" },
    { frase: "El bautismo nos hace hijos de Dios.", autor: "San Cirilo" },
    { frase: "La caridad es la reina de las virtudes.", autor: "San Basilio" },
    { frase: "La Trinidad es el misterio del amor.", autor: "San Gregorio Nacianceno" },
    { frase: "María es la Madre de Dios.", autor: "San Juan Damasceno" },
    { frase: "María es la esperanza de los pecadores.", autor: "San Sofronio" },
    { frase: "La dignidad del cristiano es grande.", autor: "San León Magno" },
    { frase: "La justicia es el fundamento de la paz.", autor: "San Gelasio I" },
    { frase: "La verdad es más fuerte que la mentira.", autor: "San Gregorio VII" },
    { frase: "El amor de Dios es el mejor de los dones.", autor: "San Bernardo" },
    { frase: "El amor de Dios es un fuego que todo lo purifica.", autor: "Santa Ángela de Foligno" },
    { frase: "El purgatorio es el amor de Dios que purifica.", autor: "Santa Catalina de Génova" },
    { frase: "La providencia de Dios nunca falla.", autor: "San Cayetano" },
    { frase: "La alegría es la mejor de las virtudes.", autor: "San Felipe Neri" },
    { frase: "La reforma comienza en el corazón.", autor: "San Carlos Borromeo" },
    { frase: "La oración es la fuerza del cristiano.", autor: "San Roberto Bellarmino" },
    { frase: "La fe es el ancla del alma.", autor: "San Pedro Canisio" },
    { frase: "La caridad es el amor en acción.", autor: "San Vicente de Paúl" },
    { frase: "La confianza en Dios es la fuente de la paz.", autor: "Santa Luisa de Marillac" },
    { frase: "El que canta, ora dos veces.", autor: "San Agustín" },
    { frase: "La educación es el camino hacia la santidad.", autor: "San Juan Bautista de La Salle" },
    { frase: "María es la mediadora de todas las gracias.", autor: "Santa Catalina Labouré" },
    { frase: "La humildad es la virtud de los santos.", autor: "Santa Bernardita" },
    { frase: "La predicación es la misión de la Iglesia.", autor: "San Antonio María Claret" },
    { frase: "Estamos en un viaje, no en una casa.", autor: "San Agustín" },
    { frase: "El secreto de confesión es sagrado.", autor: "San Juan Nepomuceno" },
    { frase: "Dios da, pero no reparte la misma dádiva a todos.", autor: "San Agustín" },
    { frase: "El amor no consiste en sentirse bien, sino en querer el bien del otro.", autor: "San Agustín" },
    { frase: "La justicia es el fundamento del reino.", autor: "San Ladislao" },
    { frase: "Conoce, oh cristiano, tu grandeza.", autor: "San León Magno" },
    { frase: "La oración es la luz del alma.", autor: "Santa Eduvigis" },
    { frase: "Quien no vive para servir, no sirve para vivir.", autor: "Santa Madre Teresa de Calcuta" },
    { frase: "La verdad es el camino hacia Dios.", autor: "San Estanislao de Cracovia" },
    { frase: "Servir a Cristo es servir al Rey.", autor: "San Wenceslao" },
    { frase: "El amor de Dios es un fuego que enciende el alma.", autor: "San Procopio" },
    { frase: "Cristo es mi luz.", autor: "San Vito" },
    { frase: "Llevar a Cristo en el corazón es la mejor aventura.", autor: "San Cristóbal" },
    { frase: "La oración es la medicina del alma.", autor: "San Pantaleón" },
    { frase: "El fruto del silencio es la oración.", autor: "Santa Madre Teresa de Calcuta" },
    { frase: "La paz comienza con una sonrisa.", autor: "Santa Madre Teresa de Calcuta" },
    { frase: "No te preocupes por los resultados, cumple con tu deber.", autor: "San Juan Bosco" },
    { frase: "No basta saber la doctrina, hay que vivirla.", autor: "San Juan Bosco" },
    { frase: "La santidad se encuentra en el deber cotidiano bien cumplido.", autor: "San Juan Bosco" },
    { frase: "Recordad que la alegría es el signo de un corazón que ama.", autor: "San Juan Bosco" },
    { frase: "La paz es el don de Dios.", autor: "San Juan XXIII" },
    { frase: "El diálogo es el camino de la Iglesia.", autor: "San Pablo VI" },
    { frase: "No tengáis miedo, abrid las puertas a Cristo.", autor: "San Juan Pablo II" },
    { frase: "El trabajo bien hecho es oración.", autor: "San Josemaría Escrivá" },
    { frase: "El amor empieza en casa.", autor: "Santa Teresa de Calcuta" },
    { frase: "El rosario es el arma para vencer al demonio.", autor: "San Pío de Pietrelcina" },
    { frase: "La oración es la fuerza del alma.", autor: "Santa Catalina de Siena" },
    { frase: "La Inmaculada es nuestra mediadora.", autor: "San Maximiliano Kolbe" },
    { frase: "La cruz es el camino hacia el cielo.", autor: "Santa Edith Stein" },
    { frase: "La Iglesia es el pueblo de Dios en marcha.", autor: "San Óscar Romero" },
    { frase: "La Eucaristía es el centro de mi vida.", autor: "Beato Carlo Acutis" },
    { frase: "La vida es un don sagrado.", autor: "Santa Gianna Beretta" },
    { frase: "La alegría es la prueba del amor.", autor: "Santa Teresa de los Andes" },
    { frase: "El silencio es el lenguaje de Dios.", autor: "Beata Isabel de la Trinidad" },
    { frase: "La santidad se encuentra en lo cotidiano.", autor: "San Rafael Arnáiz" },
    { frase: "La confianza en la misericordia de Dios es la mayor de las virtudes.", autor: "Santa Faustina" },
    { frase: "La vocación cristiana es ser sal y luz.", autor: "San Josemaría Escrivá" },
    { frase: "Si eres lo que debes ser, prenderás fuego a todo el mundo.", autor: "Santa Catalina de Siena" },
    { frase: "Haz lo que puedas, confiando en la providencia.", autor: "San Francisco de Sales" },
    { frase: "La alegría de hacer el bien es la mayor de las riquezas.", autor: "Santa María Dominga Mazzarello" },
    { frase: "El predicador debe ser el primero en vivir lo que predica.", autor: "San Juan de Ávila" },
    { frase: "El que tiene esperanza vive de otra manera.", autor: "Papa Francisco" },
    { frase: "Nadie se salva solo; como pueblo nos salvamos.", autor: "Papa Francisco" },
    { frase: "La caridad es la medida de la perfección.", autor: "San Juan de Ribera" },
    { frase: "La fe mueve montañas.", autor: "San Luis Beltrán" },
    { frase: "La verdad de Dios es la luz del alma.", autor: "San Gregorio Magno" },
    { frase: "El alma está tanto más cerca de Dios cuanto más libre de pasiones.", autor: "San Juan Crisóstomo" },
    { frase: "La Eucaristía es el tesoro más grande que Dios nos ha dejado.", autor: "San Pío de Pietrelcina" },
    { frase: "Permaneced en paz y dejad de preocuparos.", autor: "San Pío de Pietrelcina" },
    { frase: "Rezad mucho y bien.", autor: "San Pío de Pietrelcina" },
    { frase: "La constancia, no la fuerza, produce las grandes obras.", autor: "San Josemaría Escrivá" },
    { frase: "Quien ora, habla con Dios.", autor: "San Alberto Hurtado" },
    { frase: "Hay que predicar el Evangelio no solo con la palabra, sino con la vida.", autor: "San Francisco de Asís" },
    { frase: "Amemos a Dios en todo y sobre todas las cosas.", autor: "San Francisco de Asís" },
    { frase: "Reza y espera, Dios no te abandonará.", autor: "San Pío de Pietrelcina" },
    { frase: "La pequeña vía es el camino de la infancia espiritual.", autor: "Santa Teresita del Niño Jesús" },
    { frase: "La paz sea contigo.", autor: "San Francisco de Asís" },
    { frase: "Ama a Cristo, que te ama.", autor: "Santa Clara de Asís" },
    { frase: "Vive de tal modo que desees, al morir, haber vivido así.", autor: "San Ignacio de Loyola" },
    { frase: "Para mayor gloria de Dios.", autor: "San Ignacio de Loyola" },
    { frase: "En la tribulación, busca a Dios.", autor: "San Ignacio de Loyola" },
    { frase: "La semilla del Evangelio da fruto en el corazón.", autor: "San Francisco Javier" },
    { frase: "Dios me está dando este tiempo para amarle.", autor: "Santa Teresita del Niño Jesús" },
    { frase: "Jesús, ayúdame a simplificar mi vida.", autor: "Beata Teresa de Calcuta" },
    { frase: "Dios es mi capitán.", autor: "Santa Juana de Arco" },
    { frase: "Mira que te mira: no conviertas en vano su mirada.", autor: "San Juan de la Cruz" },
    { frase: "Nada sin Ti, Señor.", autor: "San Ambrosio" },
    { frase: "Dios escribe derecho en renglones torcidos.", autor: "Santa Teresa de Jesús" },
    { frase: "La fe es la luz del alma.", autor: "San Clodoveo" },
    { frase: "La fe en la Trinidad es la salvación.", autor: "Santa Bárbara" },
    { frase: "La sabiduría de Dios es infinita.", autor: "Santa Catalina de Alejandría" },
    { frase: "La fe vence al dragón.", autor: "San Jorge" },
    { frase: "Tú eres un reflejo de la luz de Dios.", autor: "Santa Hildegarda de Bingen" },
    { frase: "La Iglesia es pobre, pero tiene a Cristo.", autor: "San Lorenzo" },
    { frase: "Cristo es mi esposo.", autor: "Santa Inés" },
    { frase: "Que tu fe sea más grande que tu miedo.", autor: "San Juan Pablo II" },
    { frase: "Señor, recibe mi espíritu.", autor: "San Esteban" },
    { frase: "Es necesario que Él crezca y yo disminuya.", autor: "San Juan Bautista" },
    { frase: "Haced lo que Él os diga.", autor: "San José" },
    { frase: "Tú eres el Cristo, el Hijo de Dios vivo.", autor: "San Pedro" },
    { frase: "Para mí, la vida es Cristo.", autor: "San Pablo" },
    { frase: "Hemos encontrado al Mesías.", autor: "San Andrés" },
    { frase: "La fe sin obras está muerta.", autor: "Santiago el Mayor" },
    { frase: "Dios es amor.", autor: "San Juan Evangelista" },
    { frase: "¡Señor mío y Dios mío!", autor: "Santo Tomás apóstol" },
    { frase: "Id y enseñad a todas las naciones.", autor: "San Mateo" },
    { frase: "La fe es el fundamento de la esperanza.", autor: "San Simón y San Judas" },
    { frase: "La gracia de Dios me ha elegido.", autor: "San Matías" },
    { frase: "María conservaba todas estas cosas en su corazón.", autor: "San Lucas Evangelista" },
    { frase: "El Evangelio es la buena noticia de la salvación.", autor: "San Marcos Evangelista" },
    { frase: "La fe es el primer paso, pero el amor es la meta.", autor: "San Agustín" },
    { frase: "La caridad es la forma de todas las virtudes.", autor: "Santo Tomás de Aquino" },
    { frase: "La sabiduría es el conocimiento de las cosas eternas.", autor: "San Buenaventura" },
    { frase: "El nombre de Jesús es miel en la boca, música en el oído, alegría en el corazón.", autor: "San Bernardo" },
    { frase: "La oración es la respiración del alma.", autor: "Santa Brígida" },
    { frase: "La humildad es la verdad de la vida.", autor: "San Roberto Belarmino" },
    { frase: "La devoción a María es el camino más seguro para llegar a Jesús.", autor: "San Luis María Grignion" },
    { frase: "La música es el lenguaje del cielo.", autor: "Santa Cecilia" },
    { frase: "Los pobres son los tesoros de la Iglesia.", autor: "San Lorenzo" },
    { frase: "La virginidad es la flor del alma.", autor: "Santa Inés" },
    { frase: "El martirio es la victoria de la fe.", autor: "San Esteban" },
    { frase: "La fe es más fuerte que el miedo.", autor: "San Sebastián" },
    { frase: "El cielo es nuestra patria.", autor: "San Agustín" },
    { frase: "La alegría es el fruto del Espíritu Santo.", autor: "Santa María Mazzarello" },
    { frase: "El rosario es la oración de los humildes.", autor: "Santo Domingo de Guzmán" },
    { frase: "Nada temas, ten confianza en Dios.", autor: "San Juan de la Cruz" },
    { frase: "La humildad es la puerta de la santidad.", autor: "San Martín de Porres" },
    { frase: "Donde hay amor, allí está Dios.", autor: "Santa Teresa de Jesús" },
    { frase: "La misión es la razón de ser de la Iglesia.", autor: "San Francisco Javier" },
    { frase: "La pureza es la corona del alma.", autor: "San Luis Gonzaga" },
    { frase: "La santidad es la meta de la vida cristiana.", autor: "San Estanislao Kostka" },
    { frase: "La santidad se alcanza haciendo bien lo cotidiano.", autor: "San Juan Berchmans" },
    { frase: "La paciencia es la madre de la alegría.", autor: "San Francisco de Sales" },
    { frase: "La voluntad de Dios es mi camino.", autor: "Santa Juana de Arco" },
    { frase: "Cristo es mi fuerza.", autor: "San Patricio" },
    { frase: "La fe es el escudo del cristiano.", autor: "San Jorge" },
    { frase: "La batalla espiritual se gana con la oración.", autor: "San Miguel Arcángel" },
    { frase: "La guía de Dios es siempre segura.", autor: "San Rafael Arcángel" },
    { frase: "Anunciar la Buena Nueva es la misión del cristiano.", autor: "San Gabriel Arcángel" },
    { frase: "La oración es el abrazo del alma con Dios.", autor: "Santa Gertrudis" },
    { frase: "La humildad es el camino hacia la gloria.", autor: "Santa Matilde" },
    { frase: "Creer para entender, entender para creer.", autor: "San Anselmo" },
    { frase: "La naturaleza es el libro de Dios.", autor: "San Alberto Magno" },
    { frase: "La creación es un reflejo de la gloria de Dios.", autor: "Santa Hildegarda" },
    { frase: "La caridad es la luz del mundo.", autor: "San Gregorio Magno" },
    { frase: "La Palabra de Dios es la espada del Espíritu.", autor: "San Jerónimo" },
    { frase: "Amad a los pobres como a Cristo.", autor: "San Vicente de Paúl" },
    { frase: "La oración es el mejor de los remedios.", autor: "San Juan Crisóstomo" },
    { frase: "La caridad comienza donde termina la justicia.", autor: "Santa Teresa de Calcuta" },
    { frase: "El bautismo es el nacimiento a la vida nueva.", autor: "San Cirilo" },
    { frase: "La caridad es la perfección del cristiano.", autor: "San Basilio" },
    { frase: "La Trinidad es el misterio de la unidad.", autor: "San Gregorio Nacianceno" },
    { frase: "María es la nueva Eva.", autor: "San Juan Damasceno" },
    { frase: "María es la puerta del cielo.", autor: "San Sofronio" },
    { frase: "La dignidad del cristiano es ser hijo de Dios.", autor: "San León Magno" },
    { frase: "La justicia es la base de la paz.", autor: "San Gelasio I" },
    { frase: "La verdad triunfa sobre la mentira.", autor: "San Gregorio VII" },
    { frase: "El amor de Dios es el mayor de los tesoros.", autor: "San Bernardo" },
    { frase: "El amor de Dios es el fuego que purifica.", autor: "Santa Ángela de Foligno" },
    { frase: "El purgatorio es la misericordia de Dios.", autor: "Santa Catalina de Génova" },
    { frase: "La providencia de Dios es mi sostén.", autor: "San Cayetano" },
    { frase: "La paciencia todo lo alcanza.", autor: "Santa Teresa de Jesús" },
    { frase: "La reforma de la Iglesia comienza en el corazón.", autor: "San Carlos Borromeo" },
    { frase: "Dios no pide obras grandes, sino corazones grandes.", autor: "San Juan Bosco" },
    { frase: "Sé luz donde haya tinieblas.", autor: "San Francisco de Asís" },
    { frase: "Cada día es una oportunidad para amar.", autor: "San Juan Pablo II" },
    { frase: "La santidad es para todos.", autor: "San Francisco de Sales" },
    { frase: "Confía en Dios y no temas.", autor: "Santa Teresa de Jesús" },
    { frase: "La educación es el camino hacia Dios.", autor: "San Juan Bautista de La Salle" },
    { frase: "El amor verdadero se demuestra con obras.", autor: "San Juan Bosco" },
    { frase: "No todos somos llamados a grandes obras, pero todos a grandes amores.", autor: "San Juan Bosco" },
    { frase: "Dios no habita en ruidos; habla en la suavidad.", autor: "San Ambrosio" },
    { frase: "Dichoso quien posee la paz de Cristo en el corazón.", autor: "San Francisco de Asís" },
    { frase: "La santidad es el proyecto más hermoso de la vida.", autor: "Beato Carlo Acutis" }
];
